name: User Story
description: Add a user story
title: "[User Story]: "
labels: ["User Story", "Backlog"]
projects: ["SyracuseUniversity/42"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for adding a User Story!
  - type: textarea
    id: As-a-User
    attributes:
      label: As a {User}
      description: Also tell us, what did you expect to happen?
      placeholder: Define user - be specific (ex. Admin, Developer, End user)
    validations:
      required: true
  - type: textarea
    id: I-want-to
    attributes:
      label: I want to
      description: Also tell the action the user needs to accomplish a goal
      placeholder: Do something
    validations:
      required: true
  - type: textarea
    id: So-that-I-can
    attributes:
      label: So that I can
      description: Tell use the goal the user needs to accomplish
      placeholder: What does the user need to accomplish
    validations:
      required: true
